deck = [
		{'name': '4', 'suit':'Spades','clean deck':False,'value':1},
		{'name': '5', 'suit':'Spades','clean deck':False,'value':2},
		{'name': '6', 'suit':'Spades','clean deck':False,'value':3},
		{'name': '7', 'suit':'Spades','clean deck':False,'value':4},
		{'name': 'Queen', 'suit':'Spades','clean deck':True,'value':5},
		{'name': 'Jack', 'suit':'Spades','clean deck':True,'value':6},
		{'name': 'King', 'suit':'Spades','clean deck':True,'value':7},
		{'name': 'A', 'suit':'Spades','clean deck':True,'value':8},
		{'name': '2', 'suit':'Spades','clean deck':True,'value':9},
		{'name': '3', 'suit':'Spades','clean deck':True,'value':10},

		{'name': '4', 'suit':'Hearts','clean deck':False,'value':1},
		{'name': '5', 'suit':'Hearts','clean deck':False,'value':2},
		{'name': '6', 'suit':'Hearts','clean deck':False,'value':3},
		{'name': '7', 'suit':'Hearts','clean deck':False,'value':4},
		{'name': 'Queen', 'suit':'Hearts','clean deck':True,'value':5},
		{'name': 'Jack', 'suit':'Hearts','clean deck':True,'value':6},
		{'name': 'King', 'suit':'Hearts','clean deck':True,'value':7},
		{'name': 'A', 'suit':'Hearts','clean deck':True,'value':8},
		{'name': '2', 'suit':'Hearts','clean deck':True,'value':9},
		{'name': '3', 'suit':'Hearts','clean deck':True,'value':10},

		{'name': '4', 'suit':'Clubs','clean deck':False,'value':1},
		{'name': '5', 'suit':'Clubs','clean deck':False,'value':2},
		{'name': '6', 'suit':'Clubs','clean deck':False,'value':3},
		{'name': '7', 'suit':'Clubs','clean deck':False,'value':4},
		{'name': 'Queen', 'suit':'Clubs','clean deck':True,'value':5},
		{'name': 'Jack', 'suit':'Clubs','clean deck':True,'value':6},
		{'name': 'King', 'suit':'Clubs','clean deck':True,'value':7},
		{'name': 'A', 'suit':'Clubs','clean deck':True,'value':8},
		{'name': '2', 'suit':'Clubs','clean deck':True,'value':9},
		{'name': '3', 'suit':'Clubs','clean deck':True,'value':10},

		{'name': '4', 'suit':'Diamonds','clean deck':False,'value':1},
		{'name': '5', 'suit':'Diamonds','clean deck':False,'value':2},
		{'name': '6', 'suit':'Diamonds','clean deck':False,'value':3},
		{'name': '7', 'suit':'Diamonds','clean deck':False,'value':4},
		{'name': 'Queen', 'suit':'Diamonds','clean deck':True,'value':5},
		{'name': 'Jack', 'suit':'Diamonds','clean deck':True,'value':6},
		{'name': 'King', 'suit':'Diamonds','clean deck':True,'value':7},
		{'name': 'A', 'suit':'Diamonds','clean deck':True,'value':8},
		{'name': '2', 'suit':'Diamonds','clean deck':True,'value':9},
		{'name': '3', 'suit':'Diamonds','clean deck':True,'value':10},
		]